In [6]:
import numpy as np

## 1)converting python list to numpy array
#############################################

In [84]:
my_list = [1, 2, 3]

In [6]:
my_array = np.array(my_list)

In [8]:
print(my_array)

[1 2 3]


In [10]:
print(type(my_array))

<class 'numpy.ndarray'>


## 2)generating data with with built-in funtions 
################################################

In [12]:
np.arange(1, 101, 1)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [14]:
newone = np.arange(1, 101, 1) 

In [20]:
print(newone)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [8]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [22]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.linspace(0, 10, 11) #evenly space

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 3)Random distribution of data
###########################################3

In [22]:
np.random.rand(10)

array([0.33629911, 0.83497354, 0.1252624 , 0.80452611, 0.67646729,
       0.6136098 , 0.50431106, 0.13630173, 0.22873917, 0.18210201])

In [24]:
np.random.rand(2, 2)

array([[0.1412752 , 0.88308012],
       [0.34544581, 0.46096639]])

In [38]:
np.random.randn(2)

array([0.56488219, 0.31705144])

In [28]:
np.random.randn(2, 2)

array([[-0.78114558,  1.65446826],
       [ 0.34318561,  1.61057493]])

In [40]:
np.random.randint(1, 100, 2)

array([32, 62])

In [42]:
np.random.randint(1, 100, (2, 2))

array([[43, 89],
       [86,  1]])

In [46]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## +useful methods and attributes
########################################

In [56]:
arr = np.arange(0, 25, 1)

In [58]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [60]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [62]:
arr.max()

24

In [64]:
arr.min()

0

In [66]:
arr.argmax()

24

In [68]:
arr.argmin()

0

In [72]:
arr.dtype

dtype('int64')

In [74]:
arr.shape

(25,)

## tip
## there are difference between (1, 25) & (25, 1)
# but it's shape will still be the same

In [95]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [97]:
arr.shape

(25,)