In [5]:
import numpy as np

In [7]:
arr = np.arange(0, 11)

In [9]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# broadcasting
##################################

1) only in numpy

In [12]:
arr[:5] = 200

In [14]:
arr 

array([200, 200, 200, 200, 200,   5,   6,   7,   8,   9,  10])

2) copy(refrence)

In [20]:
slice_of_arr = arr[:6]

In [22]:
slice_of_arr

array([200, 200, 200, 200, 200,   5])

In [24]:
slice_of_arr[:] =300 

In [26]:
slice_of_arr

array([300, 300, 300, 300, 300, 300])

In [28]:
arr

array([300, 300, 300, 300, 300, 300,   6,   7,   8,   9,  10])

3) actual copy

In [32]:
slice_of_arr2 = arr.copy()

In [34]:
slice_of_arr2[:] = 400

In [36]:
slice_of_arr2

array([400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400])

In [38]:
arr

array([300, 300, 300, 300, 300, 300,   6,   7,   8,   9,  10])

# 2D indexing 

In [41]:
arr_2d = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])

In [43]:
arr_2d

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [47]:
arr_2d[0] # first row

array([1, 2, 3])

In [49]:
arr_2d[1][1] # center element

2

In [51]:
arr_2d[1, 1] # center element

2

In [53]:
arr_2d[:2] # first two rows 

array([[1, 2, 3],
       [1, 2, 3]])

In [57]:
arr_2d[:2, 1:] # fisrt two rows & second and third column

array([[2, 3],
       [2, 3]])

# conditional selection
1) simple one 

In [64]:
arr > 10

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False])

In [72]:
bool_arr = arr > 10

In [74]:
bool_arr

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False])

In [76]:
arr[bool_arr]

array([300, 300, 300, 300, 300, 300])

2) pro one

In [79]:
arr[arr>10]

array([300, 300, 300, 300, 300, 300])